#!/bin/bash
of211
decomposePar -force 2>err_adj 1>log_adj
mpirun -np 8 adjoint7FixedFlowSimpleFoamSource -parallel 2>>err_adj 1>>log_adj
reconstructPar -latestTime 2>>err_adj 1>>log_adj
sample -latestTime 2>>err_adj 1>>log_adj
